import { toHtml } from "hast-util-to-html";
import { h } from "hastscript";
import { CheckerResult } from "todone/plugin";
import { Match } from "todone/types";
import { u } from "unist-builder";
import { GitHubContext } from "../context";
import { filePermalink } from "../permalink";
import { formatDate } from "../util/format";
import * as md from "../util/markdown";
import { createIssueData } from "./issue-data";

export interface IssueDefinition {
  todoUrl: string;
  title: string;
  body: string;
}

export interface ExpiredIssueInput {
  url: URL;
  result: CheckerResult;
  matches: readonly Match[];
}

export const generateIssue = (
  context: GitHubContext,
  { url, result, matches }: ExpiredIssueInput,
): IssueDefinition => {
  const urlString = url.toString();
  const title = `TODO: ${result.title ?? urlString}`;

  const body = md.stringify(
    u("root", [
      u("paragraph", [
        u("text", "The following TODO has expired"),
        ...(result.expirationDate
          ? [
              u("text", ` as of `),
              u(
                "html",
                toHtml(
                  h(
                    "time",
                    { datetime: result.expirationDate.toISOString() },
                    formatDate(result.expirationDate),
                  ),
                ),
              ),
            ]
          : []),
        u("text", ":"),
      ]),

      u("list", [
        u("listItem", [
          u("paragraph", [
            u("link", { url: urlString }, [
              u(
                "text",
                (!urlString.startsWith(context.server) && result.title) ||
                  urlString,
              ),
            ]),
          ]),
        ]),
      ]),

      u("paragraph", [u("text", "It is present in the following files:")]),

      u(
        "list",
        matches.map((match) => {
          const fileUrl = filePermalink(
            context,
            match.file,
            match.position.line,
          );
          const content = fileUrl
            ? u("link", { url: fileUrl }, [u("text", fileUrl)])
            : u(
                "text",
                `${match.file.localPath}:${match.position.line}:${match.position.column}`,
              );
          return u("listItem", { checked: false }, [u("paragraph", [content])]);
        }),
      ),

      u("thematicBreak", []),

      u("paragraph", [
        u("text", "This issue has been automatically created by "),
        u("inlineCode", { value: "todone" }),
        u("text", "."),
      ]),

      md.createComment(
        " Please do not edit the following comments, they are automatically generated by todone. ",
      ),

      ...createIssueData({ todoUrl: urlString }),
    ]),
  );

  return { todoUrl: urlString, title, body };
};
