name: "Setup environment"
description: "Installs the tools in the `mise.toml`"

inputs:
  yarn: { default: true }

runs:
  using: composite
  steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0

    - if: ${{ inputs.yarn }}
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        cache: "yarn"

    - if: ${{ inputs.yarn }}
      shell: bash
      run: yarn install --immutable
