[tools]
node = "24"
"npm:npm" = "latest"
zizmor = "latest"

[shell_alias]
"nx" = "yarn run -TB nx"

[settings]
lockfile = true
minimum_release_age = "7d"
idiomatic_version_file_enable_tools = ["yarn"]
