name: Continuous Integration

on:
  workflow_dispatch:
    inputs: &workflow-inputs
      publish-preview:
        description: Publish a preview release to pkg.pr.new
        type: boolean
        default: false
  workflow_call:
    inputs: *workflow-inputs

permissions:
  contents: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        task:
          - lint
          - build
          - check
          - build-docs
          - test

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: jdx/mise-action@3c2e0cf82a5b2e5249f0d3635a4d83d0ae861518 # v4.2.5

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          cache: "yarn"
      - run: yarn install --immutable

      - name: Run ${{ matrix.task }}
        run: yarn nx run-many -t ${{ matrix.task }}

      - if: ${{ matrix.task == 'build' }}
        name: Pack packages
        run: |
          folder=$(pwd)/out
          mkdir -p $folder
          yarn workspaces foreach --all --no-private pack --out $folder/%s-%v.tgz

      - if: ${{ matrix.task == 'build' }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: packages
          path: ./out/*

      - if: ${{ matrix.task == 'build' && inputs.publish-preview }}
        name: Publish to pkg.pr.new
        run:
          # zizmor: ignore[use-trusted-publishing]
          yarn dlx pkg-pr-new publish --yarn $(yarn workspaces list --no-private --json | jq -r '.location')

      - if: ${{ matrix.task == 'build-docs' }}
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: ./docs

  zizmor:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Read zizmor version
        id: read-zizmor-version
        run: echo "ZIZMOR_VERSION=$(yq -p toml '.tools.zizmor.0.version' mise.lock)" >> $GITHUB_OUTPUT

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@3dc1ecc9bcb9e94e9b2c709687979e1298497054 # v0.6.2
        with:
          version: ${{ steps.read-zizmor-version.outputs.ZIZMOR_VERSION }}
