name: Continuous Integration

on:
  workflow_dispatch:
    inputs: &workflow-inputs
      publish-preview:
        description: Publish a preview release to pkg.pr.new
        type: boolean
        default: false
  workflow_call:
    inputs: *workflow-inputs

permissions:
  contents: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          cache: "yarn"
      - run: yarn install --immutable

      - name: Build and check
        run: yarn nx run-many -t lint,build,check,build-docs,test

      - name: Pack packages
        run: |
          folder=$(pwd)/out
          mkdir -p $folder
          yarn workspaces foreach --all --no-private pack --out $folder/%s-%v.tgz

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: packages
          path: ./out/*

      - uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: ./docs

      - name: Publish to pkg.pr.new
        if: ${{ inputs.publish-preview }}
        run:
          # zizmor: ignore[use-trusted-publishing]
          yarn dlx pkg-pr-new publish --yarn $(yarn workspaces list --no-private --json | jq -r '.location')

  zizmor:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@6599ee8b7a49aef6a770f63d261d214911a7ce02 # v0.6.0
