name: Check merge queue

on:
  merge_group:

permissions:
  contents: read
  security-events: write

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml

  conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          cache: "yarn"
      - run: yarn install --immutable

      - name: Check commit titles are conventional commits
        env:
          BASE_SHA: ${{ github.event.merge_group.base_sha }}
          HEAD_SHA: ${{ github.event.merge_group.head_sha }}
        run: yarn commitlint --from "$BASE_SHA" --to "$HEAD_SHA" --verbose

  pass:
    runs-on: ubuntu-latest
    needs: [ci, conventional-commits]
    if: always()
    env:
      RESULTS: ${{ toJSON(needs.*.result) }}
    steps:
      - run:
          jq --argjson results "$RESULTS" 'all(. == "success")'
