name: Publish

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  pages: write
  id-token: write
  security-events: write

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml
    with:
      publish-preview: true

  publish-packages:
    needs: ci

    runs-on: ubuntu-latest

    environment:
      name: npm
      url: https://www.npmjs.com/org/todone

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: jdx/mise-action@9e7f7633ff6f6d6048a9418a68d48f288f50eb14 # v4.2.3

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: packages
          path: ./tarballs

      - name: Publish changed packages
        run: |
          for file in ./tarballs/*; do
            mise x npm:npm -- npm publish $file || true
          done

  publish-docs:
    needs: ci

    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      pages: write

    steps:
      - uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
