name: Run Todone

on:
  workflow_dispatch:
  schedule:
    - cron: "32 18 * * *" # Every day at a chosen random time
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: jdx/mise-action@7e36c90d9ab29c415a2384db3006f3ec8a8cc654 # v4.2.4

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          cache: "yarn"
      - run: yarn install --immutable

      - name: Build action
        run: yarn nx run-many -t build

      - name: Run todone
        env:
          NODE_OPTIONS: "--enable-source-maps"
          GITHUB_TOKEN: ${{ github.token }}
        run: yarn todone run
