name: Run Todone

on:
  workflow_dispatch:
  schedule:
    - cron: "32 18 * * *" # Every day at a chosen random time
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-run:
    runs-on: ubuntu-latest

    steps:
      - uses: $/.github/actions/setup

      - name: Build action
        run: yarn nx run-many -t build

      - name: Run todone
        env:
          NODE_OPTIONS: "--enable-source-maps"
          GITHUB_TOKEN: ${{ github.token }}
        run: yarn todone run
